### ISSUE TITLE
Curse link doesn't work

### ISSUE THREAD

**Issue by robertjdac** [dfherr/ThreatClassic2#1]
Hey - the Curse link in the README doesn't work. When I search for it on the site I can only find the original CTM. I was able to install it by downloading the zip from Github, but it would be easier for my guildmates to install through the Curse Mod addon. Thanks!

**Comment by dfherr** [comment]
Yea, I'm waiting for approval on curse. Hopefully soon(TM)

**Comment by robertjdac** [comment]
Ah ok, sorry about that. Thanks!

**Comment by Road-block** [comment]
Does LTC2 "talk" to ThreatClassic-1.0?  

It might be an idea to offer a deprecation scheme where it syncs with TC1 but reports (once per session, nothing spammy) about people running the outdated TC1 (embedded in some addon) or the previous ClassicThreatMeter so we can tell them to go update.  

I tried this in my last raid, got no errors but since the adoption is low I could only see my own threat.. which is useless atm 😝

**Comment by dfherr** [comment]
No it doesn't talk to `ThreatClassic-1.0`, because TC1 and ClassicThreatMeter can't be updated (only the author can and he is gone). Actually that's the main points of renaming it in the first place.

I was thinking about asking DBM to include a deprecation warning (they probably will bundle LibThreatClassic2), if ClassicThreatMeter is running. Adding it here doesn't really make sense and as ClassicThreatMeter can't be updated I can't add it there ;)

i could send a deprecation warning to ClassicThreatMeter users that tells them to update ClassicThreatMeter. but that would probably just cause confusion.

**Comment by Road-block** [comment]
I wasn't thinking of retrofitting ClassicThreatMeter with a warning, I realize that's impossible.  

The idea is to give a once per session warning about **other** players running the outdated ThreatClassic-1.0 library (either embedded in another addon, for example Details or TidyPlates) so the early adopters can tell their x and y guildie or co-raider to go update.  

You can register the `TC1` prefix along-side your `LTC2` and passively monitor comms from the outdated lib.  

Whether you want to use that data only to offer a warning to ThreatClassic2 users or actually use them as a way to ease the transition period is up to you.

**Comment by dfherr** [comment]
Details will hopefully update to my lib tomorrow. DBM will add my bundled lib once Details does. I will probably ask DBM to bundle a depreciation warning to all users that have ClassicThreatMeter active to update to ThreatClassic2 or Details.

I will inform other author addons to remove ThreatClassic-1.0 and update once we have that state. Details and DBM should cover the majority of the playerbase already.

**Comment by robertjdac** [comment]
I can see it potentially causing confusion, but it can be a real pain to convince guildies to install/replace addons. I can see a warning helping out that effort.

**Comment by Road-block** [comment]
> I will inform other author addons to remove ThreatClassic-1.0 and update once we have that state. Details and DBM should cover the majority of the playerbase already.

Add [Threat Plates (Classic)](https://www.curseforge.com/wow/addons/threat-plates-classic) to your list 😄 
It is a quite popular (over 100k d/l just for the latest version).

**Comment by dfherr** [comment]
it's on curse. also contacted the Threat Plates classic author
