### ISSUE TITLE
[REQ] Default Blizzard Raid frame glow when player has Aggro

### ISSUE THREAD

**Issue by petey12** [dfherr/ThreatClassic2#101]
The default blizzard raid frames after WOTLK introduced a red dot/glow when a player in the raid had a mob targeting him.

This Classic wow addon successfully replicated this, but is unfortunately no longer being updated into TBC it seems:(https://www.curseforge.com/wow/addons/classicaggrohighlight)

Would it be possible to incorporate similar functionality into your threat meter?

Thanks!

**Comment by dfherr** [comment]
I don't intend to touch raidframes in this addon. It's a completly different part of the UI and except for the fact that it's also about threat not related.

In general I suggest getting custom raid frames. The blizzard frames leave a lot to be desired, including (unless it has been fixed recently) updating health instantly rather than lagging behind. You're really handicapping yourself playing with them. Dedicated raid frame addons will have this functionality built in.
