### ISSUE TITLE
Font not set error occurs after 2.5.2 patch

### ISSUE THREAD

**Issue by csimmerman** [dfherr/ThreatClassic2#123]
Addon now doesn't work after the 2.5.2 patch. Only displays colored bars with no text. Following error is given: 

10x ThreatClassic2\core\core.lua:454: <unnamed>:SetText(): Font not set
[string "=[C]"]: in function `SetText'
[string "@ThreatClassic2\core\core.lua"]:454: in function <ThreatClassic2\core\core.lua:418>
[string "@ThreatClassic2\core\core.lua"]:840: in function `?'
[string "@ThreatClassic2\core\core.lua"]:823: in function <ThreatClassic2\core\core.lua:822>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "Threat"

**Comment by dfherr** [comment]
I don't have that problem neither with just tc2 enabled nor my regular addons enabled.

Can it be that you selected a custom font and now disabled one of your other addons that provided that font? Font setting is in appearance completely to the bottom.

**Comment by csimmerman** [comment]
> I don't have that problem neither with just tc2 enabled nor my regular addons enabled.
> 
> Can it be that you selected a custom font and now disabled one of your other addons that provided that font? Font setting is in appearance completely to the bottom.

I don't have custom fonts from other addons, it's set to Oswald and simply stopped working after the patch. Seems as though a lot of fonts are missing now when I click the drop-down. Lots of blank spaces between font options.

**Comment by dfherr** [comment]
Most addons, including TC2, use something called LibSharedMedia-3.0. If an addon wants to use a font, texture or similar it registers it with LibSharedMedia and users can then use the same font in all other addons if they wish to do so even when that addon doesn't ship with it. The only font TC2 supports and ships with is  `NotoSans-SemiCondensedBold` everything else is provided through over addons. 

Your error is caused by an issue with another addon that either isn't enabled/installed anymore, doesn't include Oswald anymore or incorrectly adds fonts to the sharedmedia.

**Comment by csimmerman** [comment]
Alrighty, will close this for now. Hopefully it'll be resolved soon.
