### ISSUE TITLE
What's the difference between ClassicThreatMeter and ThreatClassic2?

### ISSUE THREAD

**Issue by infinity8942** [dfherr/ThreatClassic2#2]
Hopes you can list the advantages of ThreatClassic2 on README file, and let more players know about it. Thanks!

**Comment by dfherr** [comment]
**Q: Why use ThreatClassic2 instead of ClassicThreatMeter?**

The author of ClassicThreatMeter left the addon with a lot of bugs, like spamming "You are not in a raid" in Alterac Valley and 25% bonus aggro for Def tanks instead of 15%. ThreatClassic2 bundles LibThreatClassic2, which comes with a ton of bug fixes and provides new boss modules for handling Onyxia and Ragnaros threat mechanics.

**Comment by infinity8942** [comment]
Thanks for the explanation.
