### ISSUE TITLE
[REQ] Profiles

### ISSUE THREAD

**Issue by Mncdk** [dfherr/ThreatClassic2#21]
Could you add profiles?

Would really love to be able to set up a global profile, so I don't have to fix the layout 10 times per realm. :)

Especially since the last update moved the addon around, it's more noticable when one has to then fix it for every character.

Thanks for the addon

**Comment by dfherr** [comment]
This was caused by https://github.com/dfherr/ThreatClassic2/issues/14 that allows you to use different settings for every character and was like a 5minute thing to implement :) repositioning is a one-time event now, because the location of the config changed.

Adding profiles sounds like a fair request anyway, I might add it in the future. But don't be afraid of updates, they shouldn't move anything around anymore ;)

**Comment by Mncdk** [comment]
#14 seems very reasonable. Good change. And I would definitely prefer bugfixes over not having to readjust the threat window. :D

I'll keep updating first chance I get.

**Comment by swetlover** [comment]
Also want a  global profile,because set for my 10 characters is too tired.

**Comment by ellisjm74** [comment]
Profiles would help immensely.  I get wanting to do different setups depending on role.  With profiles, you could set a tank & dps/heal profiles.  So then you just have to set it up twice.

**Comment by dfherr** [comment]
implemented in v2.17
