### ISSUE TITLE
[REQ] Option to display current tank as a fixed 100% threat value

### ISSUE THREAD

**Issue by karai17** [dfherr/ThreatClassic2#53]
Currently, the value of 100% is given to the person who has the most threat, not necessarily who is holding aggro. This causes a bit of a headache when trying to figure out how close you are to pulling aggro because the percentage values shift. If I am a rogue, I want to know if I am sitting at 109% threat relative to the tank, not if the tank is sitting at 92% or so threat relative to me.

My assumption of the following option was to do exactly what I stated above:

![image](https://user-images.githubusercontent.com/590332/85774301-155ed280-b6f5-11ea-89c0-c0c3a9bc9b42.png)

From what I've tested, this option doesn't seem to do anything at all, there is no difference in how threat is displayed whether it is enabled or disabled, again, as far as I've tested.

**Comment by dfherr** [comment]
I think you're mixing a view things up and draw wrong conclusions.

> Currently, the value of 100% is given to the person who has the most threat, not necessarily who is holding aggro

no this assumption is incorrect. The person who has aggro is 100%, not the person with the most threat. If you do not check the raw threat option, you will gain aggro at 100%. You might see something like Tank at 10.000 threat 100%, next person at 10500 threat 95%. Because he needs 5% more threat to gain aggro (i.e. go over 110%).

> this option doesn't seem to do anything at all, there is no difference in how threat is displayed whether it is enabled or disabled

there might be a bug there, but as I stated above all this option does is change the percentage value not the raw threat number. In the example above the list would now look like this: Person 1 at 10500 threat 105%, tank at 10.000 threat 100%. The ordering is always based on the percentages.


To make things a bit more complicated. The active tank is only an assumption based on the current threat numbers and the current target of the boss. Furthermore, the range modifier is not considered at all, but all players are assumed to be in meele range due to technical limitations that prevented me from implementing a fix for this. So, you might see people with the highest threat incorrectly shown as the active tank. However, that should be the exception with either a range player being in the 110% to 130% threat range or a player with more threat than the tank being targeted by the boss without having aggro.

To make things even more complicated, threat numbers are delayed, because they have to be send between players via chat messages and the amount of messages I can sent is limited by blizzard. If I sent to much the delay gets larger and larger.

Luckily, these problems go completely away once the threat api is reenabled with the AQ40 patch.

**Comment by karai17** [comment]
Well, I believe the bug you stated is the entire point of my issue, no? Whether that checkbox is enabled or not, Threat % never exceeds 100% and that 100% is not always the active tank. If the intent of that checkbox is for the active tank to hold a 100% threat value, which is what I am requesting in this issue, then it's not doing that as far as I can tell. If this isn't a feature request, then it's a bug report.

My expectation, whether by default or via an option, would be for the active tank to hold a fixed 100% threat and anyone who goes above that is at risk of pulling, either at 110% or 130%, depending on their proximity. We don't really need to know or care about their proximity though, only the numbers, as they should be ordered by % and the game itself knows when a hunter or a warrior pulls aggro (and the addon would then set them to 100% and recalculate the %s for everyone relative to them). The individual player who is at risk of pulling aggro, since they are the player and can do a distance check, could have an indicator warning them to slow down, but this isn't really important for raid-wide display.

**Comment by dfherr** [comment]
> If the intent of that checkbox is for the active tank to hold a 100% threat value

no, that's not at all the intent of this checkbox. The active tank has always 100% threat value regardless if the checkbox is checked or not.  The only difference is that the percentages of all other players are calculated against the threat necessary to pull aggro (10% higher than tank, unchecked) or against the raw threat of the current tank (checked).

> My expectation, whether by default or via an option, would be for the active tank to hold a fixed 100% threat
This expectation is the implemented logic for regular and raw percentages.

>  and anyone who goes above that is at risk of pulling, either at 110% or 130%, depending on their proximity.

the default (and Blizzard default) is that anyone who reaches 100% will pull aggro and the API calculates their proximity in this percentage for them. With the checkbox enabled it is exactly as you describe. You basically handle the proximity yourself instead of automatically calculating that in so pull aggro = 100%.

> the game itself knows when a hunter or a warrior pulls aggro (and the addon would then set them to 100% and recalculate the %s for everyone relative to them).

The game knows it, but the addon doesn't. The addon can only guess based on the information it has. And that is the bug I explained above. That bug isn't fixable for me, but will luckily be fixed by the reenabled threat API (in a few weeks with AQ40 patch 1.13.15) that tells me exactly who is the current tank instead of having me guess it.

>  Whether that checkbox is enabled or not, Threat % never exceeds 100% and that 100% is not always the active tank.

with the checkbox enabled threat should be able to exceed 100% and at least for me it also does:

![image](https://user-images.githubusercontent.com/6793674/85804455-f4749c80-b749-11ea-8cbe-7d04a077b253.png)

And without raw threat enabled:

![image](https://user-images.githubusercontent.com/6793674/85804632-68af4000-b74a-11ea-9f7b-66578c2423fe.png)

Notice the raw threat value. My warlock has actually 4 threat more than the imp, but he would need 46 threat to pull aggro. That's why he is displayed below the active tank and 99% threatpercent.

However, for ranges between 110% and 130% the active tank is no longer correct for the reasons I explained above (also again, this will be fixed with the 1.13.5 patch). But that should be the exception unless you have very weak tanks and very strong range dds.

**Comment by karai17** [comment]
I'll have to look into it more. I tested that checkbox and it didn't seem to make any difference to how threat was being displayed. That first screenshot is exactly what I am looking for, so I suppose I'll have to retest it. Thanks~

**Comment by dfherr** [comment]
Maybe one more bit of information:


You're correct that I can detect the proximity of the player itself. However, to correctly calculate the active tank I need to know the range of all possibly tanking players (basically all within ~25% range of the top) and I do not have access to this information. I did plan to let players send their proximity to other players via messages, but as the addon is already pushing the limits for just sending threat I never went through with implementing this additional traffic.

Since I do not have the proximity information of other players, I just assume all of them are in meele range. Now when a player in range has 111% threat, the addon considers him the active tank, sets him to 100% and a buggy display occurs. This is a known issue.

**Comment by karai17** [comment]
With the new Threat API, will you be able to reduce the amount of traffic? If so, you could probably sneak in something like *"assume everyone is within melee rangle unless they send reports stating that they are not"* to have a variable, but reduced amount of traffic coming from roughly half the raid only.

**Comment by dfherr** [comment]
With the threat api there is no more traffic. https://wowwiki.fandom.com/wiki/API_UnitDetailedThreatSituation

**Comment by karai17** [comment]
After doing some more testing, it would seem that this feature is generally inconsistent. Testing on my Hunter, I've been sending my pet in to grab aggro and holding off on attacking for a second or two. As my threat increases, I'll see both my threat go above 100% while my pet maintains aggro, and other times top threat fixes at 100% while aggro is being held by my pet.

![image](https://user-images.githubusercontent.com/590332/86120789-51a28200-baab-11ea-91bb-ad894129b0a7.png)

![image](https://user-images.githubusercontent.com/590332/86120857-6c74f680-baab-11ea-916b-fc1b6516f2b2.png)

Both of the above screenshots were taken within about 45 seconds of each other with no settings changed, just fought two mobs and my pet was tanking during them.

![image](https://user-images.githubusercontent.com/590332/86121091-ce356080-baab-11ea-918e-8796f5477a77.png)

**Comment by dfherr** [comment]
I'm not sure if you can follow what I told you. But this behavior is as expected and consistent considering all the circumstances I outlined above.

**Comment by karai17** [comment]
Yeah, I just wasn't quite sure why it was broken for 130% on personal threat (I understand why it's difficult to do that on other players). If it's gonna be fixed on the 28th for everyone, that's good. :)

**Comment by dfherr** [comment]
Because I decided it's better to handle everyone the same (i.e. consistent display across all party members), rather than introducing discrepancies by handling meele range only for the player himself.

Also being in 110 to 130% aggro range is generally an unsafe endavour.
