### ISSUE TITLE
[BUG] Hunter Pet Behaviour Change

### ISSUE THREAD

**Issue by Indigo-Red** [dfherr/ThreatClassic2#56]
### What steps will reproduce the problem?  
On a hunter, attack with pet without starting any attacks from your character. 
On previous versions, pet threat would display in the window as soon as it damaged the mob.
On the latest version, nothing appears in the threat window until your character does damage to the mob. 
- So if pet has been attacking for 5 seconds with no action from the hunter, threat window is still blank. As soon as hunter damages the mob, pet threat is shown at the correct value. Information is not being missed, it is just not being displayed.

Notes:
- Threat does not start displaying if I apply a DOT like serpent sting, only displays once damage is done
- Threat will display if mob hits hunter before pet takes aggro
- Everything is working as intended after this initial lack of information.
- This is not a addon-breaking issue, but a quality of life thing - it's nice being able to see your pet's threat lead before you start attacking. 

### What version of ThreatClassic2 are you using? (Stating 'latest' is not useful)
v2.20
Previously was using v2.12, updated due to Blizzard releasing their threat API.

### Do you have an error log of what happened?
No, since no error occurred. Should be easy to reproduce.

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)
I imagine this is linked to the change to using Blizzard's threat API rather than the old method, so it's possible that there is no fix available.

**Comment by dfherr** [comment]
This is unfortunately due to the API behavior and specially related to pets. If you did not do any damage to a mob and only your pet did, you and your pet are not considered to be on the mobs threat table (even tho you obviously are) and the API returns nothing for both of you.  I would consider this a bug on Blizzards end that is working like this forever :(.

Please update to v2.21 once it available tonight. Version 2.20 still sends threat comm messages and can impact the correctness of other addons relying on com.
